[package]
name = "bitcoin-handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
# Our libraries
settings.workspace = true
models.workspace = true

# Tracing
tracing.workspace = true

# Async
tokio.workspace = true

# Error handling
thiserror.workspace = true
